TYPE
	DUT_Slot_t : STRUCT	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"25" #3"16" *)
		MOpen : MBMOpen;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"28" #3"25" *)
		MClose : MBMClose;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"29" #3"25" *)
		MCmd : MBMCmd;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"30" #3"25" *)
		fMOpen : BOOL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"32" #3"25" *)
		fMClose : BOOL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"33" #3"25" *)
		fMCmd : BOOL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"34" #3"25" *)
		statusMOpen : UINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"35" #3"25" *)
		statusMClose : UINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"36" #3"25" *)
		statusMCmd : UINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"37" #3"25" *)
		timeout : UINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"38" #3"25" *)
		ident : UDINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"39" #3"25" *)
		device : STRING[31];	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"40" #3"25" *)
		mode : STRING[31];	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"41" #3"25" *)
		config : STRING[31];	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"42" #3"25" *)
		bConnected : BOOL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"45" #3"25" *)
		bError : BOOL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"46" #3"25" *)
		errorCode : UINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"47" #3"25" *)
		flow_meter_dut : FlowMeter_t;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"50" #3"21" *)
	END_STRUCT;
	FlowMeter_t : STRUCT	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"8" #3"16" *)
		VERSION : USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"9" #3"17" *)
		INFO_PN : USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"10" #3"17" *)
		INFO_FIRM_VER : REAL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"11" #3"17" *)
		MOD_ADDR : USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"12" #3"17" *)
		MOD_BAUD : USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"13" #3"17" *)
		MOD_TERM : USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"14" #3"17" *)
		DEBUG_UP : REAL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"16" #3"17" *)
		DEBUG_DOWN : REAL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"17" #3"17" *)
		DEBUG_AMB : REAL;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"18" #3"17" *)
		address : USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"21" #3"17" *)
		registers : ARRAY[0..31] OF USINT;	(* #1"C:/Users/sennm/Downloads/FlowMeterTestRigBR/FLowMeterTestRig/Logical/FlowMeter/Main.c" #2"22" #3"17" *)
	END_STRUCT;
END_TYPE
